# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models_py3 import CheckNameAvailabilityRequest
from ._models_py3 import CheckNameAvailabilityResponse
from ._models_py3 import DetailedInformation
from ._models_py3 import ErrorAdditionalInfo
from ._models_py3 import ErrorDetail
from ._models_py3 import ErrorResponse
from ._models_py3 import Extension
from ._models_py3 import ExtensionListResponse
from ._models_py3 import FarmBeats
from ._models_py3 import FarmBeatsExtension
from ._models_py3 import FarmBeatsExtensionListResponse
from ._models_py3 import FarmBeatsListResponse
from ._models_py3 import FarmBeatsUpdateRequestModel
from ._models_py3 import Operation
from ._models_py3 import OperationDisplay
from ._models_py3 import OperationListResult
from ._models_py3 import ProxyResource
from ._models_py3 import Resource
from ._models_py3 import SystemData
from ._models_py3 import TrackedResource
from ._models_py3 import UnitSystemsInfo


from ._azure_agri_food_rp_service_enums import (
    ActionType,
    CheckNameAvailabilityReason,
    CreatedByType,
    Origin,
    ProvisioningState,
)
from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk
__all__ = [
    'CheckNameAvailabilityRequest',
    'CheckNameAvailabilityResponse',
    'DetailedInformation',
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorResponse',
    'Extension',
    'ExtensionListResponse',
    'FarmBeats',
    'FarmBeatsExtension',
    'FarmBeatsExtensionListResponse',
    'FarmBeatsListResponse',
    'FarmBeatsUpdateRequestModel',
    'Operation',
    'OperationDisplay',
    'OperationListResult',
    'ProxyResource',
    'Resource',
    'SystemData',
    'TrackedResource',
    'UnitSystemsInfo',
    'ActionType',
    'CheckNameAvailabilityReason',
    'CreatedByType',
    'Origin',
    'ProvisioningState',
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()